In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv("titanic_data.csv")

In [5]:
df.shape

(418, 12)

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [7]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [9]:
df.describe(include="all")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,418.000000,418.000000,418.000000,418,418,332.000000,418.000000,418.000000,418,417.000000,91,418
unique,NaN,NaN,NaN,418,2,NaN,NaN,NaN,363,NaN,76,3
top,NaN,NaN,NaN,"Kelly, Mr. James",male,NaN,NaN,NaN,PC 17608,NaN,B57 B59 B63 B66,S
freq,NaN,NaN,NaN,1,266,NaN,NaN,NaN,5,NaN,3,270
mean,1100.500000,0.363636,2.265550,NaN,NaN,30.272590,0.447368,0.392344,NaN,35.627188,NaN,NaN
std,120.810458,0.481622,0.841838,NaN,NaN,14.181209,0.896760,0.981429,NaN,55.907576,NaN,NaN
min,892.000000,0.000000,1.000000,NaN,NaN,0.170000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,996.250000,0.000000,1.000000,NaN,NaN,21.000000,0.000000,0.000000,NaN,7.895800,NaN,NaN
50%,1100.500000,0.000000,3.000000,NaN,NaN,27.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,1204.750000,1.000000,3.000000,NaN,NaN,39.000000,1.000000,0.000000,NaN,31.500000,NaN,NaN
max,1309.000000,1.000000,3.000000,NaN,NaN,76.000000,8.000000,9.000000,NaN,512.329200,NaN,NaN

In [10]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [11]:
df.drop_duplicates()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [12]:
df['Age']=df['Age'].fillna(df['Age'].mean())
print(df)

     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name     Sex       Age  SibSp  \
0                                Kelly, Mr. James    male  34.50000      0
1                Wilkes, Mrs. James (Ellen Needs)  female  47.00000      1
2                       Myles, Mr. Thomas Francis    male  62.00000      0
3                                Wirz, Mr. Albert    male  27.00000      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.00000      1
..                                            ...     ...       ...    ...
413                            Spector, Mr. Woolf    male  30.27259      0
414                  Oliva y Ocana, Dona. Fermina  female  39.00000      0
415                  Saether, Mr. Simon Sivertsen    male  38.50000      0
416                           Ware, Mr. Frederick    male  30.27259      0
417                      Peter, Master. Michael J    male  30.27259      1

     Parch              Ticket      Fare Cabin Embarked
0        0              330911    7.8292   NaN        Q
1        0              363272    7.0000   NaN        S
2        0              240276    9.6875   NaN        Q
3        0              315154    8.6625   NaN        S
4        1             3101298   12.2875   NaN        S
..     ...                 ...       ...   ...      ...
413      0           A.5. 3236    8.0500   NaN        S
414      0            PC 17758  108.9000  C105        C
415      0  SOTON/O.Q. 3101262    7.2500   NaN        S
416      0              359309    8.0500   NaN        S
417      1                2668   22.3583   NaN        C

[418 rows x 12 columns]

In [13]:
df['Cabin']=df['Cabin'].fillna(df['Cabin'].mode()[0])
print(df)

     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name     Sex       Age  SibSp  \
0                                Kelly, Mr. James    male  34.50000      0
1                Wilkes, Mrs. James (Ellen Needs)  female  47.00000      1
2                       Myles, Mr. Thomas Francis    male  62.00000      0
3                                Wirz, Mr. Albert    male  27.00000      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.00000      1
..                                            ...     ...       ...    ...
413                            Spector, Mr. Woolf    male  30.27259      0
414                  Oliva y Ocana, Dona. Fermina  female  39.00000      0
415                  Saether, Mr. Simon Sivertsen    male  38.50000      0
416                           Ware, Mr. Frederick    male  30.27259      0
417                      Peter, Master. Michael J    male  30.27259      1

     Parch              Ticket      Fare            Cabin Embarked
0        0              330911    7.8292  B57 B59 B63 B66        Q
1        0              363272    7.0000  B57 B59 B63 B66        S
2        0              240276    9.6875  B57 B59 B63 B66        Q
3        0              315154    8.6625  B57 B59 B63 B66        S
4        1             3101298   12.2875  B57 B59 B63 B66        S
..     ...                 ...       ...              ...      ...
413      0           A.5. 3236    8.0500  B57 B59 B63 B66        S
414      0            PC 17758  108.9000             C105        C
415      0  SOTON/O.Q. 3101262    7.2500  B57 B59 B63 B66        S
416      0              359309    8.0500  B57 B59 B63 B66        S
417      1                2668   22.3583  B57 B59 B63 B66        C

[418 rows x 12 columns]

In [14]:
df['Fare']=df['Fare'].fillna(df['Fare'].mean())
print(df)

     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name     Sex       Age  SibSp  \
0                                Kelly, Mr. James    male  34.50000      0
1                Wilkes, Mrs. James (Ellen Needs)  female  47.00000      1
2                       Myles, Mr. Thomas Francis    male  62.00000      0
3                                Wirz, Mr. Albert    male  27.00000      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.00000      1
..                                            ...     ...       ...    ...
413                            Spector, Mr. Woolf    male  30.27259      0
414                  Oliva y Ocana, Dona. Fermina  female  39.00000      0
415                  Saether, Mr. Simon Sivertsen    male  38.50000      0
416                           Ware, Mr. Frederick    male  30.27259      0
417                      Peter, Master. Michael J    male  30.27259      1

     Parch              Ticket      Fare            Cabin Embarked
0        0              330911    7.8292  B57 B59 B63 B66        Q
1        0              363272    7.0000  B57 B59 B63 B66        S
2        0              240276    9.6875  B57 B59 B63 B66        Q
3        0              315154    8.6625  B57 B59 B63 B66        S
4        1             3101298   12.2875  B57 B59 B63 B66        S
..     ...                 ...       ...              ...      ...
413      0           A.5. 3236    8.0500  B57 B59 B63 B66        S
414      0            PC 17758  108.9000             C105        C
415      0  SOTON/O.Q. 3101262    7.2500  B57 B59 B63 B66        S
416      0              359309    8.0500  B57 B59 B63 B66        S
417      1                2668   22.3583  B57 B59 B63 B66        C

[418 rows x 12 columns]

In [15]:
cab=df["Cabin"].tolist()
print(cab)

['B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B45', 'B57 B59 B63 B66', 'E31', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B36', 'B57 B59 B63 B66', 'A21', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C78', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'D34', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'D19', 'B57 B59 B63 B66', 'A9', 'B57 B59 B63 B66', 'D15', 'B57 B59 B63 B66', 'C31', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C23 C25 C27', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'F G63', 'B57 B59 B63 B66', 'B61', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C53', 'C23 C25 C27', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'D43', 'C130', 'C132', 'B57 B59 B63 B66', 'C101', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C55 C57', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B71', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C46', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C116', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'F', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'A29', 'B57 B59 B63 B66', 'C55 C57', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'G6', 'C6', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C28', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C51', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'E46', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C54', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C97', 'B57 B59 B63 B66', 'D22', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B10', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C116', 'F4', 'E45', 'B57 B59 B63 B66', 'E52', 'D30', 'B57 B59 B63 B66', 'B58 B60', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'E34', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C62 C64', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'A11', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B11', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C80', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'F33', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C85', 'B57 B59 B63 B66', 'D37', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C86', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'E34', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'D21', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C89', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C6', 'B57 B59 B63 B66', 'C89', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B45', 'F E46', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'A34', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'D', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B26', 'C22 C26', 'B57 B59 B63 B66', 'B69', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C32', 'B57 B59 B63 B66', 'B78', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'F E57', 'F2', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'F4', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'A18', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C106', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B51 B53 B55', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'D10 D12', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'E60', 'C101', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'E50', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'E39 E41', 'B52 B54 B56', 'B57 B59 B63 B66', 'A34', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C39', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B24', 'D28', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C31', 'B57 B59 B63 B66', 'B41', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C7', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'D40', 'D38', 'B57 B59 B63 B66', 'C80', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C78', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'C105', 'B57 B59 B63 B66', 'B57 B59 B63 B66', 'B57 B59 B63 B66']

In [16]:
single_list=[item for element in cab for item in element.split()]
print(single_list)

['B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B45', 'B57', 'B59', 'B63', 'B66', 'E31', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B36', 'B57', 'B59', 'B63', 'B66', 'A21', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C78', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'D34', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'D19', 'B57', 'B59', 'B63', 'B66', 'A9', 'B57', 'B59', 'B63', 'B66', 'D15', 'B57', 'B59', 'B63', 'B66', 'C31', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C23', 'C25', 'C27', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'F', 'G63', 'B57', 'B59', 'B63', 'B66', 'B61', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C53', 'C23', 'C25', 'C27', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'D43', 'C130', 'C132', 'B57', 'B59', 'B63', 'B66', 'C101', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C55', 'C57', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B71', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C46', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C116', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'F', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'A29', 'B57', 'B59', 'B63', 'B66', 'C55', 'C57', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'G6', 'C6', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C28', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C51', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'E46', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C54', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C97', 'B57', 'B59', 'B63', 'B66', 'D22', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B10', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C116', 'F4', 'E45', 'B57', 'B59', 'B63', 'B66', 'E52', 'D30', 'B57', 'B59', 'B63', 'B66', 'B58', 'B60', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'E34', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C62', 'C64', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'A11', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B11', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C80', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'F33', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C85', 'B57', 'B59', 'B63', 'B66', 'D37', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C86', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'E34', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'D21', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C89', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C6', 'B57', 'B59', 'B63', 'B66', 'C89', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B45', 'F', 'E46', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'A34', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'D', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B26', 'C22', 'C26', 'B57', 'B59', 'B63', 'B66', 'B69', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C32', 'B57', 'B59', 'B63', 'B66', 'B78', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'F', 'E57', 'F2', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'F4', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'A18', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C106', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B51', 'B53', 'B55', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'D10', 'D12', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'E60', 'C101', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'E50', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'E39', 'E41', 'B52', 'B54', 'B56', 'B57', 'B59', 'B63', 'B66', 'A34', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C39', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B24', 'D28', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C31', 'B57', 'B59', 'B63', 'B66', 'B41', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C7', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'D40', 'D38', 'B57', 'B59', 'B63', 'B66', 'C80', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C78', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'C105', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66', 'B57', 'B59', 'B63', 'B66']

In [17]:
df['Cabin']=np.random.choice(single_list, size=len(df))
print(df)

     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name     Sex       Age  SibSp  \
0                                Kelly, Mr. James    male  34.50000      0
1                Wilkes, Mrs. James (Ellen Needs)  female  47.00000      1
2                       Myles, Mr. Thomas Francis    male  62.00000      0
3                                Wirz, Mr. Albert    male  27.00000      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.00000      1
..                                            ...     ...       ...    ...
413                            Spector, Mr. Woolf    male  30.27259      0
414                  Oliva y Ocana, Dona. Fermina  female  39.00000      0
415                  Saether, Mr. Simon Sivertsen    male  38.50000      0
416                           Ware, Mr. Frederick    male  30.27259      0
417                      Peter, Master. Michael J    male  30.27259      1

     Parch              Ticket      Fare Cabin Embarked
0        0              330911    7.8292   B69        Q
1        0              363272    7.0000    A9        S
2        0              240276    9.6875   B66        Q
3        0              315154    8.6625   B57        S
4        1             3101298   12.2875   B63        S
..     ...                 ...       ...   ...      ...
413      0           A.5. 3236    8.0500   B63        S
414      0            PC 17758  108.9000   B59        C
415      0  SOTON/O.Q. 3101262    7.2500   B66        S
416      0              359309    8.0500   B66        S
417      1                2668   22.3583   B66        C

[418 rows x 12 columns]

In [18]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [19]:
df['Age']=df['Age'].astype(int)
print(df)

     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name     Sex  Age  SibSp  Parch  \
0                                Kelly, Mr. James    male   34      0      0
1                Wilkes, Mrs. James (Ellen Needs)  female   47      1      0
2                       Myles, Mr. Thomas Francis    male   62      0      0
3                                Wirz, Mr. Albert    male   27      0      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   22      1      1
..                                            ...     ...  ...    ...    ...
413                            Spector, Mr. Woolf    male   30      0      0
414                  Oliva y Ocana, Dona. Fermina  female   39      0      0
415                  Saether, Mr. Simon Sivertsen    male   38      0      0
416                           Ware, Mr. Frederick    male   30      0      0
417                      Peter, Master. Michael J    male   30      1      1

                 Ticket      Fare Cabin Embarked
0                330911    7.8292   B69        Q
1                363272    7.0000    A9        S
2                240276    9.6875   B66        Q
3                315154    8.6625   B57        S
4               3101298   12.2875   B63        S
..                  ...       ...   ...      ...
413           A.5. 3236    8.0500   B63        S
414            PC 17758  108.9000   B59        C
415  SOTON/O.Q. 3101262    7.2500   B66        S
416              359309    8.0500   B66        S
417                2668   22.3583   B66        C

[418 rows x 12 columns]

In [20]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34,0,0,330911,7.8292,B69,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47,1,0,363272,7.0000,A9,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62,0,0,240276,9.6875,B66,Q
3,895,0,3,"Wirz, Mr. Albert",male,27,0,0,315154,8.6625,B57,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22,1,1,3101298,12.2875,B63,S

In [21]:
df["Cabin"].max()

'F4'

In [22]:
#Print first 4 columns 
df.iloc[:, 0:4]

,PassengerId,Survived,Pclass,Name
0,892,0,3,"Kelly, Mr. James"
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)"
2,894,0,2,"Myles, Mr. Thomas Francis"
3,895,0,3,"Wirz, Mr. Albert"
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)"
...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf"
414,1306,1,1,"Oliva y Ocana, Dona. Fermina"
415,1307,0,3,"Saether, Mr. Simon Sivertsen"
416,1308,0,3,"Ware, Mr. Frederick"
417,1309,0,3,"Peter, Master. Michael J"

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          418 non-null    int64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         418 non-null    float64
 10  Cabin        418 non-null    object
 11  Embarked     418 non-null    object
dtypes: float64(1), int64(6), object(5)
memory usage: 39.3+ KB

In [24]:
#Print no of survivers
df[df["Survived"].isin([1])]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47,1,0,363272,7.0000,A9,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22,1,1,3101298,12.2875,B63,S
6,898,1,3,"Connolly, Miss. Kate",female,30,0,0,330972,7.6292,C64,Q
8,900,1,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18,0,0,2657,7.2292,B66,C
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23,1,0,21228,82.2667,B57,S
...,...,...,...,...,...,...,...,...,...,...,...,...
409,1301,1,3,"Peacock, Miss. Treasteall",female,3,1,1,SOTON/O.Q. 3101315,13.7750,B57,S
410,1302,1,3,"Naughton, Miss. Hannah",female,30,0,0,365237,7.7500,B66,Q
411,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37,1,0,19928,90.0000,B66,Q
412,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28,0,0,347086,7.7750,B66,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39,0,0,PC 17758,108.9000,B59,C

In [25]:
#male
df1=df[df["Sex"].isin(["male"])]
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34,0,0,330911,7.8292,B69,Q
2,894,0,2,"Myles, Mr. Thomas Francis",male,62,0,0,240276,9.6875,B66,Q
3,895,0,3,"Wirz, Mr. Albert",male,27,0,0,315154,8.6625,B57,S
5,897,0,3,"Svensson, Mr. Johan Cervin",male,14,0,0,7538,9.2250,B63,S
7,899,0,2,"Caldwell, Mr. Albert Francis",male,26,1,1,248738,29.0000,B66,S
...,...,...,...,...,...,...,...,...,...,...,...,...
407,1299,0,1,"Widener, Mr. George Dunton",male,50,1,1,113503,211.5000,B66,C
413,1305,0,3,"Spector, Mr. Woolf",male,30,0,0,A.5. 3236,8.0500,B63,S
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38,0,0,SOTON/O.Q. 3101262,7.2500,B66,S
416,1308,0,3,"Ware, Mr. Frederick",male,30,0,0,359309,8.0500,B66,S
417,1309,0,3,"Peter, Master. Michael J",male,30,1,1,2668,22.3583,B66,C

In [26]:
#female
df2=df[df["Sex"].isin(["female"])]
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47,1,0,363272,7.0000,A9,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22,1,1,3101298,12.2875,B63,S
6,898,1,3,"Connolly, Miss. Kate",female,30,0,0,330972,7.6292,C64,Q
8,900,1,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18,0,0,2657,7.2292,B66,C
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23,1,0,21228,82.2667,B57,S
...,...,...,...,...,...,...,...,...,...,...,...,...
409,1301,1,3,"Peacock, Miss. Treasteall",female,3,1,1,SOTON/O.Q. 3101315,13.7750,B57,S
410,1302,1,3,"Naughton, Miss. Hannah",female,30,0,0,365237,7.7500,B66,Q
411,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37,1,0,19928,90.0000,B66,Q
412,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28,0,0,347086,7.7750,B66,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39,0,0,PC 17758,108.9000,B59,C

In [27]:
#age
df[(df["Age"]>20)&(df["Age"]<35)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34,0,0,330911,7.8292,B69,Q
3,895,0,3,"Wirz, Mr. Albert",male,27,0,0,315154,8.6625,B57,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22,1,1,3101298,12.2875,B63,S
6,898,1,3,"Connolly, Miss. Kate",female,30,0,0,330972,7.6292,C64,Q
7,899,0,2,"Caldwell, Mr. Albert Francis",male,26,1,1,248738,29.0000,B66,S
...,...,...,...,...,...,...,...,...,...,...,...,...
410,1302,1,3,"Naughton, Miss. Hannah",female,30,0,0,365237,7.7500,B66,Q
412,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28,0,0,347086,7.7750,B66,S
413,1305,0,3,"Spector, Mr. Woolf",male,30,0,0,A.5. 3236,8.0500,B63,S
416,1308,0,3,"Ware, Mr. Frederick",male,30,0,0,359309,8.0500,B66,S
417,1309,0,3,"Peter, Master. Michael J",male,30,1,1,2668,22.3583,B66,C